import * as THREE from "three";import {mat} from "./AssetManager.js";
function box(c,s,p){const m=new THREE.Mesh(new THREE.BoxGeometry(...s),mat(c));m.position.set(...p);m.castShadow=true;m.receiveShadow=true;return m}function label(text){const c=document.createElement("canvas"),x=c.getContext("2d");c.width=512;c.height=96;x.fillStyle="#fff8e8";x.font="bold 34px Microsoft YaHei";x.fillText(text,16,58);const t=new THREE.CanvasTexture(c),s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.scale.set(4,0.75,1);return s}
export class SceneManager{constructor(scene,assets){this.scene=scene;this.assets=assets;this.root=null;this.items=[];this.current=""}clear(){if(this.root){this.scene.remove(this.root);this.root.traverse(o=>{if(o.geometry)o.geometry.dispose()})}this.root=new THREE.Group();this.scene.add(this.root);this.items=[]}add(o,id,radius=5,extra={}){this.root.add(o);if(id)this.items.push({id,object:o,radius,...extra});return this.items.at(-1)}async upgradeAsset(key,item,factory){if(!item)return;const replacement=await this.assets.loadAssetOrPlaceholder(key,factory);replacement.position.copy(item.object.position);replacement.rotation.copy(item.object.rotation);replacement.scale.copy(item.object.scale);this.root.remove(item.object);this.root.add(replacement);item.object=replacement}base(){this.root.add(box(0x83b968,[150,.2,150],[0,-.15,0]));this.root.add(box(0xb7a985,[9,.12,125],[0,.02,0]));for(let x of [-30,30])for(let z of [-30,0,30])this.root.add(box(0xc68e62,[12,4,10],[x,2,z]));for(let i=0;i<8;i++){const t=new THREE.Group();t.add(new THREE.Mesh(new THREE.CylinderGeometry(.35,.5,4,8),mat(0x76502c)));const crown=new THREE.Mesh(new THREE.ConeGeometry(2.4,4,8),mat(0x3d8148));crown.position.y=4;t.add(crown);t.position.set(-58+i*16,0,-45+(i%2)*18);this.root.add(t)}}
  gate(){const g=new THREE.Group();g.add(box(0xc6733e,[24,12,4],[0,6,-52]));g.add(box(0xe0a85b,[7,18,5],[-8,9,-52]));g.add(box(0xe0a85b,[7,18,5],[8,9,-52]));g.add(box(0x7f3e2c,[28,2,7],[0,13,-52]));g.add(label("友谊关关楼"));g.children.at(-1).position.set(0,18,-52);return g}
  grandpa(){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.SphereGeometry(.7,12,8),mat(0xf0bd91)));g.children[0].position.y=2.3;g.add(box(0x7b9d91,[1.2,1.7,0.8],[0,1.1,0]));const hat=new THREE.Mesh(new THREE.CylinderGeometry(1,1,.25,16),mat(0x2c5f52));hat.position.y=2.9;g.add(hat);g.add(label("👴 界碑爷爷"));g.children.at(-1).position.set(0,4,0);return g}
  stone(){const g=new THREE.Group();g.add(box(0xd4d1bd,[2,4,.8],[0,2,0]));g.add(box(0x9d9885,[3,.5,1.5],[0,.25,0]));g.add(label("友谊关界碑"));g.children.at(-1).position.set(0,4.8,0);return g}
  loadFriendship(){this.clear();this.base();const gateItem=this.add(this.gate(),"friendship_gate",7,{actionLabel:"查看关楼",knowledge:"友谊关关楼依托山地与道路，承担着通行、守护和交流的历史作用。"});const s=this.stone();s.position.set(0,0,18);const stoneItem=this.add(s,"boundary-stone",6,{actionLabel:"观察界碑",knowledge:"界碑是边界和历史记忆的重要见证。"});const p=this.grandpa();p.position.set(0,0,30);const grandpaItem=this.add(p,"grandpa",6);const flag=box(0xc64e3b,[.3,7,.3],[12,3,10]);this.add(flag,"flag",5,{actionLabel:"观察旗杆",knowledge:"旗帜是国家主权和共同记忆的象征。"});const exit=box(0x3d704e,[3,2,3],[-18,1,52]);this.add(exit,"frontier-entry",6,{actionLabel:"前往边境哨所"});this.upgradeAsset("friendshipGate",gateItem,()=>this.gate());this.upgradeAsset("boundaryStone",stoneItem,()=>this.stone());this.upgradeAsset("grandpa",grandpaItem,()=>this.grandpa());this.current="friendship-pass";return this.items}
  loadPost(){this.clear();this.base();this.root.add(box(0x718e98,[9,5,9],[0,2,-28]));this.root.add(box(0x8b6a3d,[5,12,5],[22,6,-30]));for(let x of [-18,-9,0,9,18])this.root.add(box(0x725036,[.3,1,.3],[x,.5,5]));this.add(box(0xc64e3b,[3,2,3],[0,1,22]),"return-pass",6,{actionLabel:"返回友谊关"});this.add(box(0x77705e,[2,5,2],[-20,2,0]),"tower",6,{actionLabel:"观察哨所",knowledge:"瞭望哨帮助守边人员观察山谷、道路与远处山脊。"});this.current="frontier-post";return this.items}
  switchScene(id){return id==="friendship-pass"?this.loadFriendship():this.loadPost()}
}
